### ISSUE TITLE
Different folder for includes

### ISSUE THREAD

**Issue by asacarter** [kalimatas/php-liquid#92]
How can I set a different folder for templates that are included with the include tag within a template?

**Comment by sanmai** [comment]
That is actually super easy to do with your own custom file system.

```php
$fs = new \Liquid\FileSystem\Virtual(function ($templatePath) {
	if ($templatePath == 'foo') {
		return "Contents of foo";
	}

	if ($templatePath == 'bar') {
		return file_get_contents('/tmp/bar');
	}

        // Here can be anything!

	return '';
});

$template = new \Liquid\Template();
$template->setFileSystem($fs);
$template->parse("{% include 'foo' %}");
$output = $template->render(array("name" => "Example"));

var_dump($output); // string(15) "Contents of foo"
```
Will that work for you?

**Comment by asacarter** [comment]
What I wanted to do was parse a template from a /template folder. When the include tag is used within that template, look for the file to parse in the other folder such as /snippets.

**Comment by edwardoka** [comment]
One solution would be a custom include tag and a custom filesystem that aggregates other filesystems and exposes a method for selecting which one you want to use.

Your custom tag class would also need to know about this method and switch filesystem.

I've put together a couple of gists to demonstrate. Not terribly elegant or covered by any unit tests because I wasn't sure whether it would work but it seems to do what you want.

[FileSystemAggregate.php](https://gist.github.com/edwardoka/05bd7c9940a9a7fa4d60465f02afa2b5)
[CustomTagInclude.php](https://gist.github.com/edwardoka/2b4be783e68d9ac1c42f7ac573ad8362)

**templates/index.liquid**
`{% include 'foo' %}`

**includes/foo.liquid**
`Hello, {{ name }}`

Calling code:
```php
$fs = new FileSystemAggregate();
$fs->addFileSystem('templates', new \Liquid\LocalFileSystem('./templates'));
$fs->addFileSystem('include_filesystem', new \Liquid\LocalFileSystem('./includes'));
$fs->select('templates');

\Liquid\Liquid::set('INCLUDE_SUFFIX', 'liquid');
\Liquid\Liquid::set('INCLUDE_PREFIX', '');
\Liquid\Liquid::set('INCLUDE_ALLOW_EXT', false);

$template = new \Liquid\Template();
$template->setFileSystem($fs);
$template->registerTag('include', 'CustomTagInclude');
$template->parseFile('index');

$output = $template->render(array("name" => "Example"));
var_dump($output); // string(14) "Hello, Example"
```
