### ISSUE TITLE
Pagination page number out of bounds

### ISSUE THREAD

**Issue by asacarter** [kalimatas/php-liquid#94]
There is no validation to check the current page is greater than the last page in the pagination.

It should point to data from the last page.

**Comment by sanmai** [comment]
How can I reproduce this issue?

**Comment by asacarter** [comment]
If the number of pages is 4 for example, and the URL is /?page=5, (or greater than 5) the result is an empty data set.

It would make more sense to default the paging results to the last page.

**Comment by edwardoka** [comment]
Regarding the page key being configurable, I've raised a PR for this. If accepted then you would call
`\Liquid\Liquid::set('PAGINATION_CONTEXT_KEY', 'newpagekey');` during the Liquid setup.
It would then look for the 'newpagekey' key in your assigned data instead of 'page' to determine which page is the current one.

This PR also contains a lookup for the request key to remove the reliance on a hardcoded 'page' in '?page=9' in the next and previous URLs.

Going back to your first point, I feel that an empty data set is the correct behaviour; if you were to do pagination in e.g. SQL you wouldn't expect `SELECT * FROM articles LIMIT 10,5` to return articles 6 through 10 if there were only 10 articles in the database.

I've added a test case to confirm that if you're on the last page then the paginate.next array is not available to the template, so someone would only go out of bounds by changing the query string by hand.

**Comment by edwardoka** [comment]
Thinking about it, another way of handling your out of bounds issue would be for the paging code to throw a specific exception that contains some data about the pagination. This would allow your application to catch these and redirect to the last page, rather than returning the last page silently.

I'm new to open source so think that implementing such a thing without consulting maintainers would be a really good way to start on a bad footing 😁

**Comment by sanmai** [comment]
Overall this doesn't seems like an issue for a template language, does it?

(In my experience people usually add rubbish to a page number when they copy and paste it from or to somewhere else. In this case getting the last page of results will be most surprising. So I'd return the first page instead in case of out-of-bounds error. And this is also cheaper DB-wise.)

**Comment by asacarter** [comment]
Agreed, the first page of data would be better than an empty set. This is also the case for all other nonsensical data added to the page parameter.
